### ISSUE TITLE
The blobs are too old.

### ISSUE THREAD

**Issue by GuaiYiHu** [tiger-cave/proprietary_vendor_xiaomi#1]

**Comment by javichampi** [comment]
Here are the most updated blobs that I've found for all devices. https://github.com/TheMuppets
Maybe we can use some of them (mako, cancro, hammerhead, graphics libs from qcom). Xiaomi seems won't update anymore our official ROM to a higher android version than Lollipop.

**Comment by GuaiYiHu** [comment]
give up give up and give up. oreo for aries boots, and never will the bugs be fixed

**Comment by javichampi** [comment]
Even using MIUI lollipop blobs we fall in more problems than with this old blobs. It's mad.

**Comment by GuaiYiHu** [comment]
wake up wake up and wake up. say goodbye to mi2~~~~~~~
